import { User, Project, Task, CalendarEvent, Department, TimelineEvent } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Nguyễn Văn An',
    email: 'an.nguyen@company.com',
    avatar: '/avatars/an.jpg',
    role: 'admin',
    department: 'IT',
  },
  {
    id: '2',
    name: 'Trần Thị Bình',
    email: 'binh.tran@company.com',
    avatar: '/avatars/binh.jpg',
    role: 'manager',
    department: 'Marketing',
  },
  {
    id: '3',
    name: 'Đinh Hồng Đức',
    email: 'duc.dinh@company.com',
    avatar: '/avatars/duc.jpg',
    role: 'employee',
    department: 'IT',
  },
  {
    id: '4',
    name: 'Phạm Thị Dung',
    email: 'dung.pham@company.com',
    avatar: '/avatars/dung.jpg',
    role: 'employee',
    department: 'HR',
  },
  {
    id: '5',
    name: 'Võ Văn Em',
    email: 'em.vo@company.com',
    avatar: '/avatars/em.jpg',
    role: 'employee',
    department: 'Sales',
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Thiết kế giao diện người dùng',
    description: 'Thiết kế wireframe và mockup cho trang chủ website',
    status: 'in-progress',
    priority: 'high',
    assignee: mockUsers[2],
    reporter: mockUsers[1],
    projectId: '1',
    startDate: new Date('2024-01-15'),
    dueDate: new Date('2024-01-25'),
    estimatedHours: 40,
    actualHours: 20,
    dependencies: [],
    tags: ['design', 'ui/ux'],
    comments: [],
    attachments: [],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    title: 'Phát triển API backend',
    description: 'Xây dựng các endpoint API cho module quản lý người dùng',
    status: 'todo',
    priority: 'high',
    assignee: mockUsers[2],
    reporter: mockUsers[0],
    projectId: '1',
    startDate: new Date('2024-01-20'),
    dueDate: new Date('2024-02-05'),
    estimatedHours: 60,
    dependencies: ['1'],
    tags: ['backend', 'api'],
    comments: [],
    attachments: [],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: '3',
    title: 'Viết test cases',
    description: 'Viết unit test và integration test cho các API',
    status: 'todo',
    priority: 'medium',
    assignee: mockUsers[3],
    reporter: mockUsers[0],
    projectId: '1',
    startDate: new Date('2024-02-01'),
    dueDate: new Date('2024-02-10'),
    estimatedHours: 30,
    dependencies: ['2'],
    tags: ['testing', 'qa'],
    comments: [],
    attachments: [],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Hệ thống CRM mới',
    description: 'Phát triển hệ thống quản lý khách hàng cho công ty',
    status: 'in-progress',
    priority: 'high',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-06-30'),
    progress: 35,
    manager: mockUsers[1],
    members: [mockUsers[2], mockUsers[3]],
    tasks: mockTasks,
    budget: 500000000,
    department: 'IT',
    createdAt: new Date('2023-12-15'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    name: 'Chiến dịch Marketing Q1',
    description: 'Triển khai chiến dịch marketing cho quý 1 năm 2024',
    status: 'planning',
    priority: 'medium',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-04-30'),
    progress: 10,
    manager: mockUsers[1],
    members: [mockUsers[4]],
    tasks: [],
    budget: 200000000,
    department: 'Marketing',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    name: 'Đào tạo nhân viên mới',
    description: 'Chương trình đào tạo cho nhân viên mới gia nhập công ty',
    status: 'completed',
    priority: 'low',
    startDate: new Date('2023-11-01'),
    endDate: new Date('2023-12-31'),
    progress: 100,
    manager: mockUsers[3],
    members: [mockUsers[4]],
    tasks: [],
    budget: 50000000,
    department: 'HR',
    createdAt: new Date('2023-10-15'),
    updatedAt: new Date('2024-01-02'),
  },
];

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: '1',
    title: 'Họp đánh giá dự án CRM',
    description: 'Đánh giá tiến độ và thảo luận các vấn đề của dự án CRM',
    start: new Date('2024-01-25T09:00:00'),
    end: new Date('2024-01-25T10:30:00'),
    type: 'meeting',
    projectId: '1',
    attendees: [mockUsers[0], mockUsers[1], mockUsers[2]],
    location: 'Phòng họp A',
    isAllDay: false,
  },
  {
    id: '2',
    title: 'Deadline thiết kế UI',
    description: 'Hoàn thành thiết kế giao diện người dùng',
    start: new Date('2024-01-25T17:00:00'),
    end: new Date('2024-01-25T17:00:00'),
    type: 'deadline',
    projectId: '1',
    taskId: '1',
    isAllDay: false,
  },
  {
    id: '3',
    title: 'Milestone: Hoàn thành phase 1',
    description: 'Hoàn thành giai đoạn 1 của dự án CRM',
    start: new Date('2024-02-15T00:00:00'),
    end: new Date('2024-02-15T23:59:59'),
    type: 'milestone',
    projectId: '1',
    isAllDay: true,
  },
];

export const mockDepartments: Department[] = [
  {
    id: '1',
    name: 'Công nghệ thông tin',
    manager: mockUsers[0],
    members: [mockUsers[0], mockUsers[2]],
    budget: 2000000000,
  },
  {
    id: '2',
    name: 'Marketing',
    manager: mockUsers[1],
    members: [mockUsers[1], mockUsers[4]],
    budget: 1000000000,
  },
  {
    id: '3',
    name: 'Nhân sự',
    manager: mockUsers[3],
    members: [mockUsers[3]],
    budget: 500000000,
  },
];

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: '1',
    title: 'Bắt đầu dự án CRM',
    description: 'Khởi động dự án hệ thống CRM mới',
    date: new Date('2024-01-01T08:00:00'),
    type: 'project-start',
    projectId: '1',
    userId: '1',
  },
  {
    id: '2',
    title: 'Hoàn thành nghiên cứu thị trường',
    description: 'Đã hoàn thành báo cáo nghiên cứu thị trường Q4',
    date: new Date('2024-01-15T16:30:00'),
    type: 'task-completed',
    projectId: '2',
    taskId: '5',
    userId: '4',
  },
  {
    id: '3',
    title: 'Họp đánh giá dự án',
    description: 'Họp đánh giá tiến độ các dự án đang thực hiện',
    date: new Date('2024-01-20T14:00:00'),
    type: 'meeting',
    userId: '1',
  },
];
